#!/usr/bin/env bash
#SBATCH --job-name=opsd_train
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:4
#SBATCH --cpus-per-gpu=12
#SBATCH --mem-per-gpu=80G
#SBATCH --time=20:00:00
#SBATCH --output=logs/%x-%A.out

# =============================================================================
# On-Policy Self-Distillation (TRL-based) training launcher.
#
# Based on "Self-Distillation Enables Continual Learning" - https://arxiv.org/abs/2601.19897
# Original implementation: https://github.com/idanshen/Self-Distillation
#
# KEY CONCEPT: TRUE ON-POLICY self-distillation
# - Teacher = frozen copy of the student checkpoint; sees prompt + gold
#   demonstration (privileged context)
# - Student sees the prompt only
# - Completions are GENERATED by the student during training (on-policy)
# - Student matches the teacher's token distribution via generalized JSD
#
# Defaults below are the settings shared by the paper's OPSD runs; per-run
# settings are exported by submit_experiment.sh.
#
# Usage:
#   sbatch --export=BASE_MODEL=...,TRAIN_PATH=...,PROMPT_KEY=...,GOLD_ANSWER_KEY=... \
#       slurm/train.sh
# =============================================================================

# --- Configuration & environment setup ---------------------------------------
source slurm/config.sh
[ -f slurm/cluster_env.sh ] && source slurm/cluster_env.sh
mkdir -p logs
source envs/train/.venv/bin/activate
export PYTHONUNBUFFERED=1

export WANDB_PROJECT=${WANDB_PROJECT:-"rethinking-opsd"}

# --- OPSD configuration -------------------------------------------------------
OPSD_ALPHA=${OPSD_ALPHA:-0.5}                    # 0=fwd KL, 1=rev KL, 0.5=JSD
OPSD_BETA=${OPSD_BETA:-0.0}                      # KL penalty to base model (unused: 0)
OPSD_SYNC_REF_MODEL=${OPSD_SYNC_REF_MODEL:-False}  # frozen teacher (no EMA)
OPSD_REF_MODEL_SYNC_STEPS=${OPSD_REF_MODEL_SYNC_STEPS:-1}
OPSD_REF_MODEL_MIXUP_ALPHA=${OPSD_REF_MODEL_MIXUP_ALPHA:-0.01}

# Generation settings (on-policy student rollouts via colocated vLLM)
OPSD_NUM_GENERATIONS=${OPSD_NUM_GENERATIONS:-1}
OPSD_GENERATE_FROM_TEACHER=${OPSD_GENERATE_FROM_TEACHER:-False}
OPSD_MAX_PROMPT_LENGTH=${OPSD_MAX_PROMPT_LENGTH:-25000}   # dense contexts; sparse runs use 8192
OPSD_MAX_COMPLETION_LENGTH=${OPSD_MAX_COMPLETION_LENGTH:-4096}
OPSD_TEMPERATURE=${OPSD_TEMPERATURE:-1.0}
OPSD_TEACHER_TEMPERATURE=${OPSD_TEACHER_TEMPERATURE:-""}
OPSD_TOP_P=${OPSD_TOP_P:-1.0}
OPSD_TOP_K=${OPSD_TOP_K:-50}
ENABLE_THINKING=${ENABLE_THINKING:-"default"}
FORCE_THINKING_PREFIX=${FORCE_THINKING_PREFIX:-""}
USE_VLLM=${USE_VLLM:-True}

# Data settings: student prompt column + gold demonstration column
PROMPT_KEY=${PROMPT_KEY:-"prompt"}
GOLD_ANSWER_KEY=${GOLD_ANSWER_KEY:-"answer"}

# Teacher prompt template override (used by the conciseness-control run)
TEACHER_PROMPT_TEMPLATE="${TEACHER_PROMPT_TEMPLATE:-}"

# Wrong-rollout gate (contrastive OPSD)
GATE_MODE=${GATE_MODE:-none}
GATE_MAX_REGEN_ROUNDS=${GATE_MAX_REGEN_ROUNDS:-3}
GATE_REQUIRE_DIFF_ANSWER=${GATE_REQUIRE_DIFF_ANSWER:-True}
GATE_GOLD_ANSWER_KEY=${GATE_GOLD_ANSWER_KEY:-""}
GATE_WRONG_ANSWER_KEY=${GATE_WRONG_ANSWER_KEY:-""}

# Training hyperparameters
OPSD_LR=${OPSD_LR:-5e-6}
OPSD_EPOCHS=${OPSD_EPOCHS:-1}
OPSD_MICRO_BATCH_SIZE=${OPSD_MICRO_BATCH_SIZE:-1}
OPSD_GRADIENT_ACCUM=${OPSD_GRADIENT_ACCUM:-8}

# --- Checkpoint path ----------------------------------------------------------
model_basename=$(basename "$BASE_MODEL")
data_basename=$(basename "${DATASET_NAME:-opsd_data}")
OPSD_TRUE_BATCH_SIZE=$(( SLURM_GPUS_ON_NODE * OPSD_MICRO_BATCH_SIZE * OPSD_GRADIENT_ACCUM ))
MPL_SUFFIX=""
if [ "${OPSD_MAX_PROMPT_LENGTH}" -ne 4096 ] 2>/dev/null; then
    MPL_SUFFIX="__mpl${OPSD_MAX_PROMPT_LENGTH}"
fi
FT_SUFFIX=""
if [ -n "${FORCE_THINKING_PREFIX}" ]; then
    FT_SUFFIX="__ft"
fi
NOTHINK_SUFFIX=""
if [ "${ENABLE_THINKING}" = "false" ]; then
    NOTHINK_SUFFIX="__nothink"
fi
GATE_SUFFIX=""
if [ "${GATE_MODE}" != "none" ]; then
    GATE_SUFFIX="__gate_${GATE_MODE}"
fi
export OPSD_CHECKPOINT_PATH="checkpoints/opsd__m_${model_basename}__d_${data_basename}__alpha${OPSD_ALPHA}__bs${OPSD_TRUE_BATCH_SIZE}__lr${OPSD_LR}__ep${OPSD_EPOCHS}${MPL_SUFFIX}${FT_SUFFIX}${NOTHINK_SUFFIX}${GATE_SUFFIX}"
mkdir -p "$OPSD_CHECKPOINT_PATH"

echo "=============================================="
echo "[OPSD] On-Policy Self-Distillation Training"
echo "=============================================="
echo "Model: $BASE_MODEL"
echo "Dataset: $TRAIN_PATH (prompt=$PROMPT_KEY, gold=$GOLD_ANSWER_KEY)"
echo "Alpha (KL type): $OPSD_ALPHA (0=fwd, 1=rev, 0.5=JSD)"
echo "Teacher sync (EMA): $OPSD_SYNC_REF_MODEL"
echo "Max prompt/completion length: $OPSD_MAX_PROMPT_LENGTH / $OPSD_MAX_COMPLETION_LENGTH"
echo "Teacher prompt template: ${TEACHER_PROMPT_TEMPLATE:-<default>}"
echo "Enable thinking: $ENABLE_THINKING | Force thinking prefix: ${FORCE_THINKING_PREFIX:-<none>}"
echo "LR: $OPSD_LR | Epochs: $OPSD_EPOCHS | Batch: $OPSD_TRUE_BATCH_SIZE (${SLURM_GPUS_ON_NODE}x${OPSD_MICRO_BATCH_SIZE}x${OPSD_GRADIENT_ACCUM}) | Warmup: ${WARMUP_RATIO}"
echo "Checkpoint: $OPSD_CHECKPOINT_PATH"
echo "=============================================="

# Match HF Trainer reporting to the W&B environment (transformers errors if
# report_to=wandb is paired with WANDB_DISABLED).
OPSD_REPORT_TO=${OPSD_REPORT_TO:-${REPORT_TO:-wandb}}
if [[ "${WANDB_DISABLED:-}" =~ ^([Tt]rue|TRUE|1|[Yy]es|YES)$ ]]; then
    OPSD_REPORT_TO="none"
elif [[ "${WANDB_MODE:-}" == "disabled" && "${OPSD_REPORT_TO}" == "wandb" ]]; then
    OPSD_REPORT_TO="none"
fi

# --- Port configuration -------------------------------------------------------
MASTER_PORT=${MASTER_PORT:-$(comm -23 <(seq 49152 65535 | sort) <(ss -Htan | awk '{print $4}' | cut -d':' -f2 | sort -u) | shuf | head -n 1)}
OPSD_GPU_COUNT=${GPU_COUNT:-${SLURM_GPUS_ON_NODE:-$(nvidia-smi -L | wc -l)}}

# --- Execution ------------------------------------------------------------------
train() {
    torchrun \
        --nproc-per-node "${OPSD_GPU_COUNT}" \
        --master_port "${MASTER_PORT}" \
        train.py \
        --model_name="${BASE_MODEL}" \
        --tokenizer_name="${BASE_TOKENIZER}" \
        --train_file_path="${TRAIN_PATH}" \
        --prompt_key="${PROMPT_KEY}" \
        --gold_answer_key="${GOLD_ANSWER_KEY}" \
        --output_dir="${OPSD_CHECKPOINT_PATH}" \
        --alpha="${OPSD_ALPHA}" \
        --beta="${OPSD_BETA}" \
        --sync_ref_model="${OPSD_SYNC_REF_MODEL}" \
        --ref_model_sync_steps="${OPSD_REF_MODEL_SYNC_STEPS}" \
        --ref_model_mixup_alpha="${OPSD_REF_MODEL_MIXUP_ALPHA}" \
        --generate_from_teacher="${OPSD_GENERATE_FROM_TEACHER}" \
        --num_generations="${OPSD_NUM_GENERATIONS}" \
        --max_prompt_length="${OPSD_MAX_PROMPT_LENGTH}" \
        --max_completion_length="${OPSD_MAX_COMPLETION_LENGTH}" \
        --temperature="${OPSD_TEMPERATURE}" \
        ${OPSD_TEACHER_TEMPERATURE:+--teacher_temperature="${OPSD_TEACHER_TEMPERATURE}"} \
        --top_p="${OPSD_TOP_P}" \
        --top_k="${OPSD_TOP_K}" \
        --per_device_train_batch_size="${OPSD_MICRO_BATCH_SIZE}" \
        --gradient_accumulation_steps="${OPSD_GRADIENT_ACCUM}" \
        --num_train_epochs="${OPSD_EPOCHS}" \
        --max_steps="${MAX_STEPS:--1}" \
        --learning_rate="${OPSD_LR}" \
        --warmup_ratio="${WARMUP_RATIO:-0.03}" \
        --lr_scheduler_type="cosine" \
        --bf16=True \
        --logging_steps=1 \
        --save_strategy="no" \
        --seed="${SEED:-42}" \
        --report_to="${OPSD_REPORT_TO}" \
        --gradient_checkpointing=True \
        --fsdp="full_shard auto_wrap" \
        --fsdp_config="${FSDP_CONFIG}" \
        --use_vllm="${USE_VLLM}" \
        --vllm_gpu_memory_utilization="${VLLM_GPU_MEM_UTIL:-0.3}" \
        --vllm_enable_sleep_mode="${VLLM_SLEEP_MODE:-True}" \
        ${TEACHER_PROMPT_TEMPLATE:+--teacher_prompt_template="${TEACHER_PROMPT_TEMPLATE}"} \
        ${FORCE_THINKING_PREFIX:+--force_thinking_prefix="${FORCE_THINKING_PREFIX}"} \
        --loss_max_completion_tokens="${LOSS_MAX_COMPLETION_TOKENS:-0}" \
        --jsd_chunk_size="${JSD_CHUNK_SIZE:-0}" \
        --gate_mode="${GATE_MODE}" \
        --gate_max_regen_rounds="${GATE_MAX_REGEN_ROUNDS}" \
        --gate_require_diff_answer="${GATE_REQUIRE_DIFF_ANSWER}" \
        ${GATE_GOLD_ANSWER_KEY:+--gate_gold_answer_key="${GATE_GOLD_ANSWER_KEY}"} \
        ${GATE_WRONG_ANSWER_KEY:+--gate_wrong_answer_key="${GATE_WRONG_ANSWER_KEY}"} \
        --enable_thinking="${ENABLE_THINKING}"
}

# Skip training if the checkpoint already exists (resume-friendly pipelines).
if [[ -f "${OPSD_CHECKPOINT_PATH}/config.json" || -f "${OPSD_CHECKPOINT_PATH}/adapter_config.json" ]]; then
    echo "Checkpoint found at ${OPSD_CHECKPOINT_PATH}. Skipping training."
    EXIT_CODE=0
else
    train
    EXIT_CODE=$?
fi

echo "[OPSD] Training finished with exit code: $EXIT_CODE"
exit $EXIT_CODE
